export const images = {
  gif1: require('../../assets/gifs/gif1.webp'),
  splashscreen: require('../../assets/gifs/splashscreen.gif'),
  profileDummy:
    'http://test1.pillersofttechnologies.com/assets/images/profile.png',
  coverDummy: 'http://test1.pillersofttechnologies.com/assets/images/cover.png',
  requestBg:require('../../assets/icons/requestbg.png'),
  suggestionBg:require('../../assets/icons/suggestionBg.png'),
  helpbg:require('../../assets/icons/helpBg.png')
};

export const icons = {
  Intro1: require('../../assets/icons/loginIcon.png'),
  introBottom: require('../../assets/icons/introBottom.png'),
  IntroRightArrow: require('../../assets/icons/IntroRightArrow.png'),
  view: require('../../assets/icons/view.png'),
  hide: require('../../assets/icons/hide.png'),
  radioFill: require('../../assets/icons/radioFill.png'),
  radioBlank: require('../../assets/icons/radioBlank.png'),
  downArrow: require('../../assets/icons/downArrow.png'),
  tab1: require('../../assets/icons/tab1.png'),
  tab2: require('../../assets/icons/tab2.png'),
  tab3: require('../../assets/icons/tab3.png'),
  tab4: require('../../assets/icons/tab4.png'),
  tab5: require('../../assets/icons/tab5.png'),
  tab6: require('../../assets/icons/tab6.png'),
  Bg: require('../../assets/icons/Bg.png'),
  searchIcon: require('../../assets/icons/searchIcon.png'),
  notificationIcon: require('../../assets/icons/notificationIcon.png'),
  chatIcon: require('../../assets/icons/chatIcon.png'),
  markerIcon: require('../../assets/icons/markerIcon.png'),
  CategoryIcon: require('../../assets/icons/CategoryIcon.png'),
  sellIcon: require('../../assets/icons/sellIcon.png'),
  icon1: require('../../assets/icons/1.png'),
  icon2: require('../../assets/icons/2.png'),
  icon3: require('../../assets/icons/3.png'),
  icon4: require('../../assets/icons/4.png'),
  backIcon: require('../../assets/icons/backIcon.png'),
  demoUser: require('../../assets/icons/demoUser.png'),
  AddPhoto: require('../../assets/icons/AddPhoto.png'),
  closeBtn: require('../../assets/icons/closeBtn.png'),
  cat1: require('../../assets/icons/cat1.png'),
  BuyItemIcon: require('../../assets/icons/BuyItemIcon.png'),
  FollowIcon: require('../../assets/icons/FollowIcon.png'),
  ListingIcon: require('../../assets/icons/ListingIcon.png'),
  MessgaeIcon: require('../../assets/icons/MessgaeIcon.png'),
  filterIcon: require('../../assets/icons/filterIcon.png'),
  rec1: require('../../assets/icons/rec1.png'),
  chatIconwithColor: require('../../assets/icons/chatIconwithColor.png'),
  demoUser1: require('../../assets/icons/demoUser1.png'),
  horizontalThreeDot: require('../../assets/icons/horizontalThreeDot.png'),
  sendMessageIcon: require('../../assets/icons/sendMessageIcon.png'),
  dummyUser: require('../../assets/icons/dummyUser.png'),
  product1: require('../../assets/icons/product1.png'),
  editIcon: require('../../assets/icons/editIcon.png'),
  followingIocn: require('../../assets/icons/followingIocn.png'),
  commentIcon: require('../../assets/icons/commentIcon.png'),
  likeIcon: require('../../assets/icons/likeIcon.png'),
  Photoicon: require('../../assets/icons/Photoicon.png'),
  GalleryIcon: require('../../assets/icons/GalleryIcon.png'),
  horizontalDot: require('../../assets/icons/horizontalDot.png'),
  AttchmentIcon: require('../../assets/icons/AttchmentIcon.png'),
  editPencilBlue: require('../../assets/icons/editPencilBlue.png'),
  certified: require('../../assets/icons/certified.png'),
  cameraIcon: require('../../assets/icons/cameraIcon.png'),
  badgeIcon: require('../../assets/icons/badgeIcon.png'),
  peopleIcon: require('../../assets/icons/peopleIcon.png'),
  emailIcon: require('../../assets/icons/emailIcon.png'),
  callIcon: require('../../assets/icons/callIcon.png'),
  AddFollowicon: require('../../assets/icons/AddFollowicon.png'),
  currencyIcon: require('../../assets/icons/currenctIcon.png'),
  workIcon: require('../../assets/icons/workIcon.png'),
  locationIcon: require('../../assets/icons/locationIcon.png'),
  GivenratingIcon: require('../../assets/icons/GivenratingIcon.png'),
  expIcon: require('../../assets/icons/expIcon.png'),
  LikeFillIcon: require('../../assets/icons/LikeFillIcon.png'),
  RectangleIcon: require('../../assets/icons/RectangleIcon.png'),
  suggestionIcon: require('../../assets/icons/suggestionIcons.png'),
  requestIcon: require('../../assets/icons/requesticons.png'),
  helpIcon: require('../../assets/icons/helpIcons.png'),
  RightSideMoveBlueIcon: require('../../assets/icons/RightSideMoveBlueIcon.png'),
  bussinessIcon: require('../../assets/icons/bussinessIcon.png'),
  TraininggIcon: require('../../assets/icons/TraininggIcon.png'),
  trash: require('../../assets/icons/trash.png'),
  reportIcon: require('../../assets/icons/reportIcon.png'),
  blockIcon: require('../../assets/icons/blockIcon.png'),
  checkMark: require('../../assets/icons/checkMark.png'),
  skillCloseBtn: require('../../assets/icons/skillCloseBtn.png'),
  addIcon: require('../../assets/icons/addIcon.png'),
  successProposalIcon: require('../../assets/icons/successProposalIcon.png'),
  chatWithColorIcon: require('../../assets/icons/chatWithColorIcon.png'),
  send: require('../../assets/icons/send.png'),
  cake: require('../../assets/icons/cake.png'),
  home: require('../../assets/icons/home.png'),
  girl: require('../../assets/icons/girl.png'),
  smallRight: require('../../assets/icons/small-right.png'),

  request: require('../../assets/icons/request.png'),
  star: require('../../assets/icons/star.png'),
  infoI: require('../../assets/icons/info-i.png'),
  help: require('../../assets/icons/help.png'),
  setting: require('../../assets/icons/setting.png'),
  helpQuestion: require('../../assets/icons/helpQuestion.png'),

  delete: require('../../assets/icons/delete.png'),
  edit: require('../../assets/icons/edit.png'),
  close: require('../../assets/icons/close.png'),
  suggestion: require('../../assets/icons/suggestions.png'),
  link: require('../../assets/icons/link.png'),
  emailOpen: require('../../assets/icons/email-open.png'),
  arrowRight:require('../../assets/icons/arrowRight.png'),
  Logout:require('../../assets/icons/Logout.png'),
  community:require('../../assets/icons/community.png'),
  send_fill:require('../../assets/icons/send_fill.png'),
  profile_notify:require('../../assets/icons/profile_notify.png'),
  france: require('../../assets/icons/france.png'),
  english: require('../../assets/icons/english.png'),
  german: require('../../assets/icons/german.png'),
};
export const onboardingImages = [
  {
    bg: require('../../assets/icons/introbg.png'),
    image: require('../../assets/icons/intro1.png'),
  },
  {
    bg: require('../../assets/icons/introbg.png'),
    image: require('../../assets/icons/intro2.png'),
  },
  {
    bg: require('../../assets/icons/introbg.png'),
    image: require('../../assets/icons/intro3.png'),
  },
  
];